verbs = [["b i","w a s t","b i I N","b I n","\\ae m","I z"],
         ["h \\ae v","h \\ae d","h \\ae v I N","h a v e d","h \\ae v","h \\ae v z"],
         ["d u","d i d s t","d u I N","d @ n","d 5 T","d @ z"],
         ["s e","s E d","s e I N","s E d","s e","s E z"],
         ["k \\ae n","c o u l d s t","k \\ae n I N","k \\ae n d","k \\ae n","k \\ae n"],
         ["w I l","w U d","w I l I N","w I l d","w I l","w I l"],
         ["g o","g o e d","g o I N","g 5 n","g o","g o z"],
         ["g E t","g a t","g E t I N","g a t","g E t","g E t s"],
         ["m e k","m e d","m e k I N","m e d","m e k","m e k s"],
         ["n o","n u","n o I N","n o n","n o","n o z"],
         ["s i","s 5","s i I N","s i n","s i","s i z"],
         ["T I N k","T 5 t","T I N k @ N","T 5 t","T I N k","T I N k s"],
         ["k @ m","k e m","k @ m I N","k @ m","k @ m","k @ m z"],
         ["t e k","t U k","t e k I N","t e k @ n","t e k","t e k s"],
         ["l U k","l U k t","l U k I N","l U k t","l U k","l U k s"],
         ["g I v","g e v","g I v I N","g I v @ n","g I v","g I v z"],
         ["w a n t","w 5 n t @ d","w a n t I N","w 5 n t @ d","w a n t","w a n t s"],
         ["f a j n d","f a w n d","f a j n d I N","f a w n d","f a j n d","f a j n d z"],
         ["t E l","t o l d","t E l I N","t o l d","t E l","t E l z"],
         ["j u s","j u z d","j u z I N","j u z d","j u s","j u s @ z"],
         ["s i m","s i m d","s i m I N","s i m d","s i m","s i m z"],
         ["f i l","f E l t","f i l I N","f E l t","f i l","f i l z"],
         ["b I k @ m","b I k e m","b I k @ m I N","b I k @ m","b I k @ m","b I k @ m z"],
         ["\\ae s k","\\ae s k t","\\ae s k I N","\\ae s k t","\\ae s k","\\ae s k s"],
         ["p U t","p U t","p @ t I N","p U t","p U t","p U t s"],
         ["l i v","l E f t","l i v I N","l E f t","l i v","l i v z"],
         ["t r a j","t r a j d","t r a j I N","t r a j d","t r a j","t r a j z"],
         ["m i n","m E n t","m i n I N","m E n t","m i n","m i n z"],
         ["k 5 l","k 5 l d","k 5 l I N","k 5 l d","k 5 l","k 5 l z"],
         ["b I g I n","b I g \\ae n","b I g I n I N","b I g @ n","b I g I n","b I g I n z"],
         ["k i p","k E p t","k i p I N","k E p t","k i p","k i p s"],
         ["t @ r n","t @ r n d","t @ r n I N","t @ r n d","t @ r n","t @ r n z"],
         ["n i d","n i d @ d","n i d I N","n i d @ d","n i d","n i d z"],
         ["w @ r k","w @ r k t","w @ r k I N","w @ r k t","w @ r k","w @ r k s"],
         ["l a j v","l a j v d","l I v I N","l a j v d","l a j v","l I v z"],
         ["b r I N","b r 5 t","b r I N I N","b r 5 t","b r I N","b r I N z"],
         ["t 5 k","t 5 k t","t 5 k I N","t 5 k t","t 5 k","t 5 k s"],
         ["h I r","h @ r d","h I r I N","h @ r d","h I r","h I r z"],
         ["s I t","s \\ae t","s I t I N","s \\ae t","s I t","s I t s"],
         ["S o","S o d","S o I N","S o d","S o","S o z"],
         ["s t \\ae n d","s t U d","s t \\ae n d I N","s t U d","s t \\ae n d","s t \\ae n d z"],
         ["h o l d","h E l d","h o l d I N","h E l d","h o l d","h o l d z"],
         ["r a j t","r o t","r a j t I N","r I t @ n","r a j t","r a j t s"],
         ["t S e n d Z","t S e n d Z d","t S e n d Z I N","t S e n d Z d","t S e n d Z","t S e n d Z @ z"],
         ["s t a r t","s t a r t @ d","s t a r t I N","s t a r t @ d","s t a r t","s t a r t s"],
         ["r @ n","r \\ae n","r @ n I N","r @ n","r @ n","r @ n z"],
         ["h \\ae p @ n","h \\ae p @ n d","h \\ae p @ n I N","h \\ae p @ n d","h \\ae p @ n","h \\ae p @ n z"],
         ["l E t","l E t","l E t I N","l E t","l E t","l E t s"],
         ["m u v","m u v d","m u v I N","m u v d","m u v","m u v z"],
         ["b @ l i v","b @ l i v d","b @ l i v I N","b @ l i v d","b @ l i v","b @ l i v z"],
         ["p l e","p l e d","p l e I N","p l e d","p l e","p l e z"],
         ["h E l p","h E l p t","h E l p I N","h E l p t","h E l p","h E l p s"],
         ["r E d","r E d","r E d I N","r E d","r E d","r i d z"],
         ["s p i k","s p o k","s p i k I N","s p o k @ n","s p i k","s p i k s"],
         ["r @ m E m b @ r","r @ m E m b @ r d","r @ m E m b @ r I N","r @ m E m b @ r d","r @ m E m b @ r","r @ m E m b @ r z"],
         ["p e","p e d","p e I N","p e d","p e","p e z"],
         ["g r o","g r u","g r o I N","g r o n","g r o","g r o z"],
         ["l u z","l 5 s t","l u z I N","l 5 s t","l u z","l u z @ z"],
         ["s t a p","s t a p t","s t a p I N","s t a p t","s t a p","s t a p s"],
         ["l a j k","l a j k t","l a j k I N","l a j k t","l a j k","l a j k s"],
         ["l a j","l a j d","l a j I N","l e n","l a j","l a j z"],
         ["w e t","w e t @ d","w e t I N","w e t @ d","w e t","w e t s"],
         ["s E t","s E t","s E t I N","s E t","s E t","s E t s"],
         ["k \\ae r i","k \\ae r i d","k \\ae r i I N","k \\ae r i d","k \\ae r i","k \\ae r i z"],
         ["w a k","w 5 k t","w 5 k I N","w 5 k t","w a k","w 5 k s"],
         ["l @ r n","l @ r n t","l @ r n I N","l @ r n t","l @ r n","l @ r n z"],
         ["f a l o","f a l o d","f a l o I N","f a l o d","f a l o","f a l o z"],
         ["l E d","l E d","l i d I N","l E d","l E d","l i d z"],
         ["f a l","f E l","f a l I N","f a l l e d","f a l","f 5 l z"],
         ["@ p I r","@ p I r d","@ p I r I N","@ p I r d","@ p I r","@ p I r z"],
         ["@ n d @ r s t \\ae n d","@ n d @ r s t U d","@ n d @ r s t \\ae n d I N","@ n d @ r s t U d","@ n d @ r s t \\ae n d","@ n d @ r s t \\ae n d z"],
         ["i t","e t","i t I N","i t @ n","i t","i t s"],
         ["I k s p E k t","I k s p E k t @ d","I k s p E k t I N","I k s p E k t @ d","I k s p E k t","I k s p E k t s"],
         ["s p E n d","s p E n t","s p E n d I N","s p E n t","s p E n d","s p E n d z"],
         ["s E n d","s E n t","s E n d I N","s E n t","s E n d","s E n d z"],
         ["@ l a w","@ l a w d","@ l a w I N","@ l a w d","@ l a w","@ l a w z"],
         ["k @ n t I n j u","k @ n t I n j u d","k @ n t I n j u I N","k @ n t I n j u d","k @ n t I n j u","k @ n t I n j u z"],
         ["r @ m e n","r @ m e n d","r @ m e n I N","r @ m e n d","r @ m e n","r @ m e n z"],
         ["p \\ae s","p \\ae s t","p \\ae s I N","p \\ae s t","p \\ae s","p \\ae s @ z"],
         ["p r @ v a j d","p r @ v a j d @ d","p r @ v a j d I N","p r @ v a j d @ d","p r @ v a j d","p r @ v a j d z"],
         ["b a j","b a t","b a j I N","b a t","b a j","b a j z"],
         ["r i t S","r i t S t","r i t S I N","r i t S t","r i t S","r i t S @ z"],
         ["d I v E l @ p","d I v E l @ p t","d I v E l @ p I N","d I v E l @ p t","d I v E l @ p","d I v E l @ p s"],
         ["s t e","s t e d","s t e I N","s t e d","s t e","s t e z"],
         ["w a t S","w a t S t","w a t S I N","w a t S t","w a t S","w a t S @ z"],
         ["d @ s a j d","d @ s a j d @ d","d @ s a j d I N","d @ s a j d @ d","d @ s a j d","d @ s a j d z"],
         ["p r @ d u s","p r @ d u s t","p r @ d u s I N","p r @ d u s t","p r @ d u s","p r @ d u s @ z"],
         ["w E r","w 0 r","w E r I N","w 0 r n","w E r","w E r z"],
         ["b I l d","b I l t","b I l d I N","b I l t","b I l d","b I l d z"],
         ["d a j","d a j d","d a j I N","d a j d","d a j","d a j z"],
         ["l @ v","l @ v d","l @ v I N","l @ v d","l @ v","l @ v z"],
         ["\\ae d","\\ae d @ d","\\ae d I N","\\ae d @ d","\\ae d","\\ae d z"],
         ["m i t","m E t","m i t I N","m E t","m i t","m i t s"],
         ["I n k r i s","I n k r i s t","I n k r i s I N","I n k r i s t","I n k r i s","I n k r i s @ z"],
         ["o p @ n","o p @ n d","o p @ n I N","o p @ n d","o p @ n","o p @ n z"]]
